[package]
name = "simple_hmd_clean"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
openvr-driver = { path = "../../openvr-driver" }
tracing = "0.1"
tracing-subscriber = "0.3"
once_cell = "1.19"
parking_lot = "0.12"

[profile.release]
opt-level = 2
lto = true
