[package]
name = "pure_rust_driver"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
openvr-driver-bindings = { path = "../../openvr-driver-bindings" }
driver-macros = { path = "../../driver-macros" }
log = "0.4"
once_cell = "1.19"

[features]
default = []
